services:
  db:
   build:
     context: .
     dockerfile: dockerfile
     target: release
   volumes:
     # BUG: https://github.com/microsoft/mssql-docker/issues/735
     # run: sudo chown 10001:10001 mssql2022/
     - /home/ozzie/Development/db/mssql2022:/var/opt/mssql
   ports:
     - 11433:1433
