# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  playstorecatalogservice:
    image: playstorecatalogservice
    build:
      context: .
      dockerfile: Playstore.Catalog.Service/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - mongodb
      - rabbitmq

  playstoreinventoryservice:
    image: playstoreinventoryservice
    build:
      context: .
      dockerfile: Playstore.Inventory.Service/Dockerfile
    ports:
      - 8002:5002
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo:8
    ports:
      - 27017:27017
    volumes:
      - ~/Development/db/mongodb8:/data/db
    restart: always
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      # post messages to the queue
      - 5672:5672
      # access portal: username=guest, password=guest
      - 15672:15672
    volumes:
      - ~/Development/db/rabbitmq4:/var/lib/rabbitmq
    # important for persisting data in same place (random value by default)
    hostname: rabbitmq
