# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  playstorecatalogservice:
    image: playstorecatalogservice
    build:
      context: .
      dockerfile: Playstore.Catalog.Service/Dockerfile
    ports:
      - 8001:5001
    depends_on:
      - mongodb

  playstoreinventoryservice:
    image: playstoreinventoryservice
    build:
      context: .
      dockerfile: Playstore.Inventory.Service/Dockerfile
    ports:
      - 8002:5002
    depends_on:
      - mongodb

  mongodb:
    # docker run -d --rm --name mongo -p 27017:27017 -v ~/Development/db/mongodb8:/data/db mongo:8
    image: mongo:8
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ~/Development/db/mongodb8:/data/db
    restart: always
