services:

  # Nginx server as 'web' service
  web:
    build: 
      context: .
      dockerfile: ./nginx/prod.Dockerfile
    ports:
      # map localhost port 8000 to 80 inside container
      - "8000:80"

  # PHP app - configured in external docker file
  app:
    build:
      context: .
      dockerfile: ./php/prod.Dockerfile

  # MySQL DB
  db:
    image: mysql:8.0
    volumes:
      - /home/ozzie/Development/db/mysql8:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: training_docker_php