services:

  web:
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
      # target app_prod
      target: app_prod
    ports:
      - "8000:80"

  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
      # target app_prod
      target: app_prod
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: training_docker_php
      MYSQL_USER: user
      MYSQL_PASSWORD: secret 
      REDIS_HOST: cache
      REDIS_PORT: 6379

  db:
    image: mysql:8.0
    volumes:
      - /home/ozzie/Development/db/mysql8:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: training_docker_php
  cache:
    image: redis:7.4