services:
  db:
   image: mcr.microsoft.com/mssql/server:2022-latest
   environment:
     ACCEPT_EULA: Y
     SA_PASSWORD: Pwd12345!
   volumes:
     # BUG: https://github.com/microsoft/mssql-docker/issues/735
     # run: sudo chown 10001:10001 mssql2022/
     - /home/ozzie/Development/db/mssql2022:/var/opt/mssql
   ports:
     - 11433:1433
