# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  airvinyl:
    image: airvinyl
    build:
      context: .
      dockerfile: AirVinyl/Dockerfile
    ports:
      - 8000:5000
  mssql:
   image: mcr.microsoft.com/mssql/server:2022-latest
   environment:
     ACCEPT_EULA: Y
     # root user: sa
     MSSQL_SA_PASSWORD: Pwd12345!
   # Do NOT mount /var/opt/mssql as volume -> causes container to refuse login / crash
   volumes:
     - ~/Development/db/mssql2022:/var/opt/mssql/data
   ports:
     # VS code connect to: localhost,7000
     - 7000:1433
