# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  bulkybook:
    image: bulkybook
    build:
      context: .
      dockerfile: BulkyBook/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5093:5093
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
