# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  playstorecatalogservice:
    image: playstorecatalogservice
    build:
      context: .
      dockerfile: Playstore.Catalog.Service/Dockerfile
    ports:
      - 8000:5215
    depends_on:
      - mongodb
  mongodb:
    image: mongo:8
    ports:
      - 27017:27017
    volumes:
      - ~/Development/db/mongodb8:/data/db
    restart: always
